name:                Puzzle
version:             0.1.0.0
synopsis:            Utilities for programming puzzles.
description:         Written for Advent of Code, may help with other challenges. 
homepage:            https://github.com/githubuser/aoc#readme
license:             BSD3
license-file:        LICENSE
author:              Gabriel Nogueira Araujo
maintainer:          example@example.com
copyright:           2022 Gabriel Nogueira Araujo
category:            Web
build-type:          Simple
extra-source-files:  README.md

library:
  source-dirs:      src
  exposed-modules:     Puzzle.Input

  dependencies:       
  - base >= 4.7 && < 5
  - split 
  - random

executable:
  source-dirs:      app
  main:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  dependencies:       
  - base
  - Puzzle

tests:
  puzzle-test:      
    source-dirs: test
    main:             Spec.hs
  dependencies:       
  - base
  - Puzzle
  - hspec
  - QuickCheck
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N

